string_funcs : string_funcs.c
	gcc -g -Wall -o ../bin/string_funcs string_funcs.c

string_sort : string_sort.c 
	gcc -g -Wall -o ../bin/string_sort string_sort.c

pointers : pointers.c 
	gcc -g -Wall -o ../bin/pointers pointers.c

array_pointer : array_pointer.c 
	gcc -g -Wall -o ../bin/array_pointer array_pointer.c

square_me : square_me.c 
	gcc -g -Wall -o ../bin/square_me square_me.c

string_len : string_len.c 
	gcc -g -Wall -o ../bin/string_len string_len.c

string_malloc : string_malloc.c 
	gcc -g -Wall -o ../bin/string_malloc string_malloc.c
