string_funcs : string_funcs.c
	gcc -g -Wall -o ../bin/string_funcs string_funcs.c

string_sort : string_sort.c 
	gcc -g -Wall -o ../bin/string_sort string_sort.c

pointers : pointers.c 
	gcc -g -Wall -o ../bin/pointers pointers.c

